# Generated by Django 4.0.6 on 2022-07-29 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='object_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Flower.flower'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='object_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='Flower.user'),
        ),
    ]
